### ISSUE TITLE
Using MID$ seems to corrupt something

### ISSUE THREAD

**Issue by Thraka** [neilsf/xc-basic3#33]
```basic
DIM t AS STRING*12
t = "  hello!  "
DIM length AS BYTE: length = len(t)
t = MID$(t, 1, length - 1)
PRINT t
```
I'm not sure exactly what is causing corruption, but this program does something bad causing the C64 in VICE to crash.

**Comment by neilsf** [comment]
Fixed. Thanks for reporting.

**Comment by Thraka** [comment]
@neilsf  that sample code is still having a problem. I've modified it to `print t` so you can see it doesn't work. If you move the calculation from the parameter of MID$ to its own line, it will start working:

```diff
  DIM t AS STRING*12
  t = "  hello!  "
  DIM length AS BYTE: length = len(t)
- t = MID$(t, 1, length - 1)
+ length = length - 1
+ t = MID$(t, 1, length)
  PRINT t
```

**Comment by neilsf** [comment]
It seems to be working for me:
![image](https://user-images.githubusercontent.com/5172851/149467061-9ce8a1fe-0eee-43ee-8251-5b94a0bd26ea.png)

**Comment by neilsf** [comment]
Previous message deleted. Okay, I can see now. Will check why it doesn't work.
